name: Evaluacion Automatica y Calidad de Código

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código del alumno
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Validar estructura del proyecto
      run: |
        echo "Verificando existencia de carpetas requeridas..."
        test -d src/unidad-1-fundamentos || exit 1
        test -d src/unidad-2-html-css || exit 1
        echo "Estructura correcta."

    - name: Análisis de Código (Linter)
      run: |
        npx --yes htmlhint "src/**/*.html" || true
        echo "Análisis finalizado."